### ISSUE TITLE
build error in XMPPIQRequest.m

### ISSUE THREAD

**Issue by billmoling** [cubewang/NewsReader#1]
https://www.evernote.com/shard/s103/sh/f56e9eff-ea43-42ad-a4ba-6ef3cc1d92d0/3a0652abe37b9052d6459f7be722134a

build error in XMPPIQRequest.m

**Comment by studentdeng** [comment]
thanks for your issue : )

we didn't notice that there were mistakes in Xcode 4.5.
but we are happy to see the Xcode's changes.
